export const  USER_ACTION_TYPE={
    SET_CURRENT:'SET_CURRENT_USER',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILED:'SIGN_IN_FAILED',
    SIGN_UP_START:'SIGN_UP_START',
    SIGN_UP_FAILED:'SIGN_UP_FAILED',
    SIGN_UP_SUCCES:'SIGN_UP_SUCCES',
    SIGN_OUT_START:'SIGN_OUT_START',
    SIGN_OUT_FAILED:'SIGN_OUT_FAILED',
    SIGN_OUT_SUCCES:'SIGN_OUT_SUCCES',

}
